Fix errors when launcing
Must be a recent change in terraform (guess), but running `./tf_instance.sh launch ubuntu` was kicking out the error:

```
Error: Error refreshing state: 1 error(s) occurred:

* data.aws_ami.ami: 1 error(s) occurred:

* data.aws_ami.ami: data.aws_ami.ami: Your query returned no results. Please change your search criteria and try again.
```

Found this update to work.